### PR TITLE
Improve requesting scan data via osp

### PR DESCRIPTION
**Pull request by bjoernricks**
Wait 5 seconds to re-request new scan data via osp.

### CODE REVIEW

**Comment by mattmundell** [comment]
I guess this needs a changelog.

**Comment by bjoernricks** [comment]
Sorry I was to fast. I am not sure about that. Before the delay was in ospd ...

**Comment by mattmundell** [comment]
No stress it's minor.

**Comment by bjoernricks** [comment]
https://github.com/greenbone/gvmd/pull/1011

**Pull request merged**
