### PR TITLE
Fix: add LIBDIR to SYSTEMD_SERVICE_DIR config

### LINKED ISSUE #2296: config/CMakeLists.txt: SYSTEMD_SYSTEM_DIR should respect LIBDIR
### Expected behavior
Systemd service file should be installed into the location where `$LIBDIR` points to

### Actual behavior
The file will always be installed into `/lib/systemd/system/`

### Steps to reproduce
Log output: (Please ignore the `/tmp/makepkg/gvmd/pkg/gvmd` part from the paths. I took the log from the output of a program which creates a distribution package.)
```
[100%] Built target gvmd
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/var/lib/gvm/gvmd
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/etc/gvm/gvmd_log.conf
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/etc/gvm/pwpolicy.conf
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/rnc.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/02052818-dab6-11df-9be4-002264764cea/rnc.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/02052818-dab6-11df-9be4-002264764cea/HTML.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/02052818-dab6-11df-9be4-002264764cea/generate
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/787a4a18-dabc-11df-9486-002264764cea/rnc.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/787a4a18-dabc-11df-9486-002264764cea/RNC.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/787a4a18-dabc-11df-9486-002264764cea/generate
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/18e826fc-dab6-11df-b913-002264764cea/GMP.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/18e826fc-dab6-11df-b913-002264764cea/generate
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/d6cf255e-947c-11e1-829a-406186ea4fc5/GMP.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_schema_formats/d6cf255e-947c-11e1-829a-406186ea4fc5/generate
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/2db07698-ec49-11e5-bcff-28d24461215b/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/4a398d42-87c0-11e5-a1c0-28d24461215b/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/c427a688-b653-40ab-a9d0-d6ba842a9d63/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/9d435134-15d3-11e6-bf5c-28d24461215b/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/cd1f5a34-6bdc-11e0-9827-002264764cea/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/5b39c481-9137-4876-b734-263849dd96ce/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/5b39c481-9137-4876-b734-263849dd96ce/report-convert.py
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/f9d97653-f89b-41af-9ba1-0f6ee00e9c1a/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/global_alert_methods/159f79a5-fce8-4ec5-aa49-7d17a77739a3/alert
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/quick_first_scan.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/get_tasks_deep.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/delete_task_deep.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/quick_auth_scan.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/quick_task.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/reset_task.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/wizards/modify_task.xml
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/scap/cpe_getbyname.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/scap/cve_getbyname.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/cert/cert_bund_getbyname.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/cert/dfn_cert_getbyname.xsl
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvm-lsc-deb-creator
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvm-lsc-exe-creator
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvm-lsc-rpm-creator
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/gvm/gvmd/template.nsis
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/bin/gvm-manage-certs
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/man/man1/gvm-manage-certs.1
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/doc/gvm/example-gvm-manage-certs.conf
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/bin/gvmd
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23.10.0
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/lib/systemd/system/gvmd.service
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/etc/logrotate.d/gvmd
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/doc/gvm/html/gmp.html
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/share/man/man8/gvmd.8
make: Leaving directory '/tmp/makepkg/gvmd/src/build'
```

Significant part:
```
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23.10.0
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/lib/systemd/system/gvmd.service
```
The shared libs are going into `/usr/lib` whereas the unit file goes into `/lib/`

### Suggested change:
Replace `/lib` with `${LIBDIR}` to https://github.com/greenbone/gvmd/blob/main/config/CMakeLists.txt#L20
```patch
--- a/gvmd-23.10.0/config/CMakeLists.txt
+++ b/gvmd-23.10.0/config/CMakeLists.txt
@@ -17,7 +17,7 @@
 
 
 if (NOT SYSTEMD_SERVICE_DIR)
-  set (SYSTEMD_SERVICE_DIR "/lib/systemd/system")
+  set (SYSTEMD_SERVICE_DIR "${LIBDIR}/systemd/system")
 endif (NOT SYSTEMD_SERVICE_DIR)
 
 if (NOT LOGROTATE_DIR)


```

Output after that change:
```
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23.10.0
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so.23
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/libgvm-pg-server.so
-- Installing: /tmp/makepkg/gvmd/pkg/gvmd/usr/lib/systemd/system/gvmd.service
```

### PR DESCRIPTION
**Pull request by mattmundell**
## What

Prefix the `SYSTEMD_SERVICE_DIR` config path with `LIBDIR`.

## Why

The default install was always putting the systemd files in `/lib`.

For one this can cause permission problems, for example if you're installing to your home dir.

Note that it's still possible to specify an exact location by passing -DSYSTEMD_SERVICE_DIR to cmake.

## Verify

On main, before the PR:
```console
#### 1 plain
$ cmake MANY_ARGS && make install
-- Installing: /lib/systemd/system/gvmd.service
CMake Error at config/cmake_install.cmake:54 (file):
  file INSTALL cannot copy file
  "/home/matt/fresh/main/build/gvmd/config/gvmd.service" to
  "/lib/systemd/system/gvmd.service": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:424 (include)
make: *** [Makefile:130: install] Error 1

#### 2 specify LIBDIR
$ cmake -DLIBDIR=/tmp/ MANY_ARGS && make install
-- Installing: /lib/systemd/system/gvmd.service
CMake Error at config/cmake_install.cmake:54 (file):
  file INSTALL cannot copy file
  "/home/matt/fresh/main/build/gvmd/config/gvmd.service" to
  "/lib/systemd/system/gvmd.service": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:424 (include)
make: *** [Makefile:130: install] Error 1
```
With the PR:
```console
#### plain
$ cmake MANY_ARGS && make install
-- Installing: /home/matt/alts/main/lib/systemd/system/gvmd.service
Compilation finished at Tue Oct  8 11:12:02

#### specify LIBDIR
$ cmake -DLIBDIR=/tmp/ MANY_ARGS && make install
-- Installing: /tmp/systemd/system/gvmd.service
Compilation finished at Tue Oct  8 11:12:57
```

## References

Closes #2296.

### CODE REVIEW

**Comment by mattmundell** [comment]
@cfi-gb I see. That explains why my cmake command has built up so many flags over the years. This seems wrong to me because:
1. I should not have to pass `-DSYSTEMD_SERVICE_DIR=$INSTALL_PREFIX/lib/systemd/system` to avoid permission errors when installing to my home dir.
2. Similarly, if I use root to install a second version to an arbitrary location it should not overwrite the /lib/systemd files from my main install.
3. According to the [manpage](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#) it makes sense to place systemd files in `/usr/local/lib/systemd/system/gvmd.service`, which is not happening when I install to /usr/local.

**Comment by mattmundell** [comment]
OK, maybe needs a broader approach, I'll look again next week.

**Comment by Narrat** [comment]
What may play a role for hardcoding `/lib` in 2021. The [usr-merge](https://wiki.debian.org/UsrMerge) wasn't covered by all major players like it is now. IIRC Debian had still a separate `/lib` back then and it would be the location for systemd. Other distros were earlier and for those `/lib/` is only a symlink to `/usr/lib/` and files shouldn't be installed into /lib anymore. Some package managers may even refuse to install such a package (contains a directory for a location which is only a symlink).
From experience as someone who dabs into maintaing recipes to create packages for package manager it is fairly normal, that specifying `LIBDIR` places the files relative to that position even if those are for another piece of software. The commit in question even allows to modify `/etc` to whatever, which may make sense or not as a location.

I also noticed that the same happens for another package, but I only opened it for this package to see what happens. If the reaction was positive a follow up issue would have been made. But that seems obsolete now?

**Comment by bjoernricks** [comment]
Hey, my intentions with https://github.com/greenbone/gvmd/pull/1662 were to use sane defaults that work out of the box without adjusting any paths even when using the default prefix `/usr/local`. The standard setting should just work without having to set a lot of variables or to tweak system configurations. IMHO this behavior should be kept. Of course paths should be adjusted if they aren't valid anymore like if `/lib/systemd` is `/usr/lib/systemd` nowadays. I am also fine with making paths adjustable and more flexible by introducing new CMake configuration variables.

**Comment by mattmundell** [comment]
Thanks for the context @bjoernricks and @Narrat.

From what I can see, the standard settings just work, but only if you install as root, and only if you install to one place.

It's great that the standard settings are sane. Can we also have sane behaviour when I install to my home dir? For example, when INSTALL_PREFIX is `$HOME/alts/main` then SYSCONFDIR is being set to `/etc`. This to me is very poor behaviour. It will try to install somewhere that needs root, and it will overwrite any version that I've installed to `/`.

Maybe there's some conflict of requirements here because when installing to `/usr/local` the standard setting is to install to `/etc`. What is the reason for this? Why does a `/usr/local` install need to put config files like `gvm/gvmd_log.conf` in `/etc`? Does this make it easier for people following docs?

**Comment by Narrat** [comment]
`/etc` is kinda special as it is **the** location for system-wide configuration. There is not really a different location (ignoring the oddball location `/opt` which can contain `/opt/etc`, IIRC. But `/usr/local/etc` is as far as I know not a thing.
But a program should [not expect or need `/etc`](https://www.freedesktop.org/software/systemd/man/latest/file-hierarchy.html#/etc/). And with the rise of immutable distributions there may be further changes in the future (see for example this [issue](https://github.com/uapi-group/specifications/issues/76))
So in general not a problem if the configuration cannot be placed at the default location? As the program can be supplied with a path to a config?

And the difference between `/usr/local/{bin,lib,(...)}` and `/usr/{bin,lib,(...)}` stems nowadays mostly from the fact, that the latter is managed by the distribution specific package manager and no one should manually install files into that location. But `/etc` is kinda ignored and is "valid" for managed and unmanaged installations. With possible side-effects.
With that in mind I did look up again what locations systemd searches for unit files. And the hierarchy includes `/usr/local/lib/systemd/`.
https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#System%20Unit%20Search%20Path
```
System Unit Search Path

/etc/systemd/system.control/*
--
/run/systemd/system.control/*
/run/systemd/transient/*
/run/systemd/generator.early/*
/etc/systemd/system/*
/etc/systemd/system.attached/*
/run/systemd/system/*
/run/systemd/system.attached/*
/run/systemd/generator/*
…
/usr/local/lib/systemd/system/*  <---
/usr/lib/systemd/system/*
/run/systemd/generator.late/*
```
So it isn't necessary to hardcode `/lib` or update it to just `/usr/lib`. And from the viewpoint of distributions it shouldn't potentially place files in a managed area on a manual installation.

**Review by timopollmeier — APPROVED** [review]

**Comment by mattmundell** [comment]
Thanks again for the context, @Narrat.

**Pull request merged**
