### PR TITLE
Add a script to migrate old exported configs

### PR DESCRIPTION
**Pull request by mattmundell**
**Checklist**:

- [ ] Tests N/A
- [ ] [CHANGELOG](https://github.com/greenbone/gvmd/blob/master/CHANGELOG.md) Entry N/A

### CODE REVIEW

**Comment by mattmundell** [comment]
> The overall idea looks good but I wonder if it wouldn't be better if the preferences list were in an external file, with another script (or new part of the main one) to generate a new list from GMP or OSP.

I kept it to a single file so that it would be easy for people like support to use the script.

Why would they preference list need to be updated?  The pref names should not change until the old gvm versions are retired, if I understand right.  Perhaps an update would be needed when new preferences are added in the feed?

**Comment by timopollmeier** [comment]
> I kept it to a single file so that it would be easy for people like support to use the script.
> 
> Why would they preference list need to be updated? The pref names should not change until the old gvm versions are retired, if I understand right. Perhaps an update would be needed when new preferences are added in the feed?

You're right, the names should not change for now, but as new NVTs are added to the feed, so are new preferences that have to be migrated to include an id.

**Comment by bjoernricks** [comment]
>You're right, the names should not change for now, but as new NVTs are added to the feed, so are >new preferences that have to be migrated to include an id.
@cfi-gb can this ever happen? IMHO new nvts should not use name based preferences at all. Otherwise the feature has wasted a lot of our time!

**Comment by timopollmeier** [comment]
@bjoernricks : New NVTs will have an id that is used instead of the name, but only in versions of gvmd that support it.

**Comment by cfi-gb** [comment]
^ confirmed, as long as GOS 5.0 (GVM-10) is supported new VTs still need to use name based preferences (and are in addition using an id as a preparation for newer GVM versions). Such older GOS/GVM versions don't have any knowledge about the id based preferences.

**Comment by mattmundell** [comment]
> The overall idea looks good but I wonder if it wouldn't be better if the preferences list were in an external file, with another script (or new part of the main one) to generate a new list from GMP or OSP.

I've added a new script, create-gvm-migrate-config, that generates gvm-migrate-config.

This way gvm-migrate-config is remains a single file, and can be updated to match a gvmd db at any time.

**Pull request merged**
