### PR TITLE
Replace sql_severity_matches_ov with a plain plpgsql function.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
**What**:
The function severity_matches_ov() used in some SQL statements is currently
implemented in C. There is no need to do so as it converts pretty simple
to plpgsql.

**Why**:

Reducing the level of dependency to custom C functions in the database.

**How**:

The original C function is rewritten to only use plpgsql.

**Checklist**:

N/A

### CODE REVIEW

**Review by mattmundell — APPROVED** [review]

**Comment by mattmundell** [comment]
By the way "How" is for "How did you test it".  It's a bad heading.

**Comment by bjoernricks** [comment]
> By the way "How" is for "How did you test it". It's a bad heading.

Yes indeed. We should change the headline.

**Comment by bjoernricks** [comment]
Does this change need an additional migration?

**Comment by mattmundell** [comment]
> Does this change need an additional migration?

No I don't think so.  The new version will just replace the old one.

**Pull request merged**
